Add import statements to bark skill
jmillerv/mycroft2-skills pull request #9
Opened 2023-01-12 04:19 UTC by devvmh

2023-01-12 17:46 UTC, jmillerv commented
I'll check this out on my machine and see what's going on Friday Night or Saturday day. I may have had some auto-import stuff going on that didn't get committed when I created this.

2023-01-12 17:57 UTC, jmillerv requested changes
Thanks for updating the repo, I added a comment about pycache.

2023-01-12 17:57 UTC, jmillerv commented on bark.mark2/__init__.py
> +    @intent_handler('bark.intent')
Can you remove your pycachce files from this PR? I need to make a PR to update the gitignore and remove the pycache from this repo. We shouldn't be committing it. That was an oversight on my part.

2023-01-12 17:57 UTC, jmillerv commented on bark.mark2/__init__.py
> +from mycroft.skills import (
Yeah, the version on my machine matches this. I need to create a better workflow. Thanks for adding!

2023-01-13 05:43 UTC, jmillerv commented
Okay, tested locally. Yep.  Good call on the other suggestion for sym links so that what's on the machine matches the repo. 

When you remove the __pychache__ from the PR, I'll merge it.

2023-01-14 19:37 UTC, devvmh commented
Whoops! I since added pycache to my global .gitignore so should be fine next time

2023-01-14 22:38 UTC, jmillerv approved these changes

2023-01-14 22:38 UTC, merged